"""Descrição das alterações

Revision ID: 41f36ffa1b32
Revises: 
Create Date: 2025-04-01 17:52:32.326357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f36ffa1b32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('parcela', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('instituicao', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ganhos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('origem', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cartao_credito')
    op.drop_table('donativo')
    op.drop_table('ganho')
    op.drop_table('despesa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesa',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('valor', sa.FLOAT(), nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ganho',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('valor', sa.FLOAT(), nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('origem', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donativo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('valor', sa.FLOAT(), nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('instituicao', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartao_credito',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('valor', sa.FLOAT(), nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('parcela', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ganhos')
    op.drop_table('donativos')
    op.drop_table('despesas')
    op.drop_table('cartoes')
    # ### end Alembic commands ###
